#!/usr/bin/env bash
# displays infinite message and catch SIGTERM signal to print other message

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
